apiVersion: extenstions/v1beta1
kind: Deployment
metadata:
  name: sample-v1
  namespace: sample
  labels:
    app: sample
    version: v1
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: sample
        version: v1
    spec:
      containers:
        - name: sample
          image: docker.io/jocatalin/kubernetes-bootcamp:{{.Values.tag}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: sample
  labels:
    app: sample
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: sample