# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sample
# ---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample
  namespace: sample
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample
  namespace: sample
spec:
  hosts:
    - '*'
  gateways:
    - sample
  http:
    - match:
        - uri:
            prefix: '/api/v1'
      route:
        - destination:
            host: sample.sample.svc.cluster.local
            port:
              number: 8080
